@echo off
setlocal
pushd %~dp0

if not exist tools\zig-windows-x86_64-0.13.0\zig.exe (
  powershell -c Expand-Archive tools\zig-windows-x86_64-0.13.0.zip -DestinationPath tools
)

set PATH=tools\zig-windows-x86_64-0.13.0;%PATH%

zig cc ^
-o gameboy.exe ^
-ISDL/include ^
-ISDL/src/video/khronos ^
-lgdi32 ^
-lImm32 ^
-lVersion ^
-lOleAut32 ^
-lOle32 ^
-lCfgmgr32 ^
-lWinmm ^
-lSetupapi ^
-include math.h ^
-DHAVE_ATAN ^
-DHAVE_ATAN2 ^
-DHAVE_TAN ^
-DHAVE_SIN ^
-DHAVE_SQRT ^
-DHAVE_FLOOR ^
-DHAVE_COPYSIGN ^
-DHAVE_COS ^
-DHAVE_EXP ^
-DHAVE_FABS ^
-DHAVE_FMOD ^
-DHAVE_LOG ^
-DHAVE_LOG10 ^
-DHAVE_POW ^
-DHAVE_SCALBN ^
gameboy.c sound.c platform.c ^
SDL/src/SDL.c ^
SDL/src/SDL_assert.c ^
SDL/src/SDL_error.c ^
SDL/src/SDL_guid.c ^
SDL/src/SDL_log.c ^
SDL/src/SDL_dataqueue.c ^
SDL/src/SDL_hints.c ^
SDL/src/SDL_list.c ^
SDL/src/SDL_utils.c ^
SDL/src/stdlib/SDL_getenv.c ^
SDL/src/stdlib/SDL_iconv.c ^
SDL/src/stdlib/SDL_malloc.c ^
SDL/src/stdlib/SDL_qsort.c ^
SDL/src/stdlib/SDL_stdlib.c ^
SDL/src/stdlib/SDL_string.c ^
SDL/src/stdlib/SDL_strtokr.c ^
SDL/src/stdlib/SDL_crc16.c ^
SDL/src/stdlib/SDL_crc32.c ^
SDL/src/cpuinfo/SDL_cpuinfo.c ^
SDL/src/atomic/SDL_atomic.c ^
SDL/src/atomic/SDL_spinlock.c ^
SDL/src/thread/SDL_thread.c ^
SDL/src/timer/SDL_timer.c ^
SDL/src/file/SDL_rwops.c ^
SDL/src/power/SDL_power.c ^
SDL/src/audio/SDL_audio.c ^
SDL/src/audio/SDL_audiocvt.c ^
SDL/src/audio/SDL_audiodev.c ^
SDL/src/audio/SDL_audiotypecvt.c ^
SDL/src/audio/SDL_mixer.c ^
SDL/src/audio/SDL_wave.c ^
SDL/src/events/SDL_events.c ^
SDL/src/events/SDL_quit.c ^
SDL/src/events/SDL_keyboard.c ^
SDL/src/events/SDL_mouse.c ^
SDL/src/events/SDL_windowevents.c ^
SDL/src/events/SDL_clipboardevents.c ^
SDL/src/events/SDL_dropevents.c ^
SDL/src/events/SDL_displayevents.c ^
SDL/src/events/SDL_gesture.c ^
SDL/src/sensor/SDL_sensor.c ^
SDL/src/events/SDL_touch.c ^
SDL/src/haptic/SDL_haptic.c ^
SDL/src/hidapi/SDL_hidapi.c ^
SDL/src/joystick/SDL_gamecontroller.c ^
SDL/src/joystick/SDL_joystick.c ^
SDL/src/joystick/controller_type.c ^
SDL/src/render/SDL_render.c ^
SDL/src/video/yuv2rgb/yuv_rgb_sse.c ^
SDL/src/video/yuv2rgb/yuv_rgb_std.c ^
SDL/src/video/SDL_yuv.c ^
SDL/src/render/SDL_yuv_sw.c ^
SDL/src/render/software/SDL_blendfillrect.c ^
SDL/src/render/software/SDL_blendline.c ^
SDL/src/render/software/SDL_blendpoint.c ^
SDL/src/render/software/SDL_drawline.c ^
SDL/src/render/software/SDL_drawpoint.c ^
SDL/src/render/software/SDL_render_sw.c ^
SDL/src/render/software/SDL_rotate.c ^
SDL/src/render/software/SDL_triangle.c ^
SDL/src/video/SDL_blit.c ^
SDL/src/video/SDL_blit_0.c ^
SDL/src/video/SDL_blit_1.c ^
SDL/src/video/SDL_blit_A.c ^
SDL/src/video/SDL_blit_auto.c ^
SDL/src/video/SDL_blit_copy.c ^
SDL/src/video/SDL_blit_N.c ^
SDL/src/video/SDL_blit_slow.c ^
SDL/src/video/SDL_fillrect.c ^
SDL/src/video/SDL_bmp.c ^
SDL/src/video/SDL_pixels.c ^
SDL/src/video/SDL_rect.c ^
SDL/src/video/SDL_RLEaccel.c ^
SDL/src/video/SDL_shape.c ^
SDL/src/video/SDL_stretch.c ^
SDL/src/video/SDL_surface.c ^
SDL/src/video/SDL_video.c ^
SDL/src/video/SDL_clipboard.c ^
SDL/src/video/SDL_vulkan_utils.c ^
SDL/src/video/SDL_egl.c ^
SDL/src/thread/generic/SDL_syscond.c ^
SDL/src/thread/windows/SDL_sysmutex.c ^
SDL/src/thread/windows/SDL_syssem.c ^
SDL/src/thread/windows/SDL_systhread.c ^
SDL/src/thread/windows/SDL_systls.c ^
SDL/src/timer/windows/SDL_systimer.c ^
SDL/src/loadso/windows/SDL_sysloadso.c ^
SDL/src/filesystem/windows/SDL_sysfilesystem.c ^
SDL/src/haptic/dummy/SDL_syshaptic.c ^
SDL/src/joystick/dummy/SDL_sysjoystick.c ^
SDL/src/joystick/virtual/SDL_virtualjoystick.c ^
SDL/src/joystick/hidapi/SDL_hidapijoystick.c ^
SDL/src/joystick/hidapi/SDL_hidapi_rumble.c ^
SDL/src/joystick/hidapi/SDL_hidapi_combined.c ^
SDL/src/joystick/hidapi/SDL_hidapi_gamecube.c ^
SDL/src/joystick/hidapi/SDL_hidapi_luna.c ^
SDL/src/joystick/hidapi/SDL_hidapi_ps3.c ^
SDL/src/joystick/hidapi/SDL_hidapi_ps4.c ^
SDL/src/joystick/hidapi/SDL_hidapi_ps5.c ^
SDL/src/joystick/hidapi/SDL_hidapi_shield.c ^
SDL/src/joystick/hidapi/SDL_hidapi_stadia.c ^
SDL/src/joystick/hidapi/SDL_hidapi_switch.c ^
SDL/src/joystick/hidapi/SDL_hidapi_wii.c ^
SDL/src/joystick/hidapi/SDL_hidapi_xbox360.c ^
SDL/src/joystick/hidapi/SDL_hidapi_xbox360w.c ^
SDL/src/joystick/hidapi/SDL_hidapi_xboxone.c ^
SDL/src/joystick/hidapi/SDL_hidapi_steam.c ^
SDL/src/joystick/hidapi/SDL_hidapi_steamdeck.c ^
SDL/src/audio/dummy/SDL_dummyaudio.c ^
SDL/src/audio/disk/SDL_diskaudio.c ^
SDL/src/video/dummy/SDL_nullvideo.c ^
SDL/src/video/dummy/SDL_nullframebuffer.c ^
SDL/src/video/dummy/SDL_nullevents.c ^
SDL/src/sensor/dummy/SDL_dummysensor.c ^
SDL/src/locale/SDL_locale.c ^
SDL/src/locale/windows/SDL_syslocale.c ^
SDL/src/misc/SDL_url.c ^
SDL/src/misc/windows/SDL_sysurl.c ^
SDL/src/audio/winmm/SDL_winmm.c ^
SDL/src/audio/directsound/SDL_directsound.c ^
SDL/src/audio/wasapi/SDL_wasapi.c ^
SDL/src/audio/wasapi/SDL_wasapi_win32.c ^
SDL/src/core/windows/SDL_hid.c ^
SDL/src/core/windows/SDL_immdevice.c ^
SDL/src/core/windows/SDL_windows.c ^
SDL/src/core/windows/SDL_xinput.c ^
SDL/src/haptic/windows/SDL_dinputhaptic.c ^
SDL/src/haptic/windows/SDL_windowshaptic.c ^
SDL/src/haptic/windows/SDL_xinputhaptic.c ^
SDL/src/joystick/windows/SDL_dinputjoystick.c ^
SDL/src/joystick/windows/SDL_rawinputjoystick.c ^
SDL/src/joystick/windows/SDL_windowsjoystick.c ^
SDL/src/joystick/windows/SDL_windows_gaming_input.c ^
SDL/src/joystick/windows/SDL_xinputjoystick.c ^
SDL/src/power/windows/SDL_syspower.c ^
SDL/src/render/SDL_d3dmath.c ^
SDL/src/render/direct3d/SDL_render_d3d.c ^
SDL/src/render/direct3d/SDL_shaders_d3d.c ^
SDL/src/render/direct3d11/SDL_render_d3d11.c ^
SDL/src/render/direct3d11/SDL_shaders_d3d11.c ^
SDL/src/render/direct3d12/SDL_render_d3d12.c ^
SDL/src/render/direct3d12/SDL_shaders_d3d12.c ^
SDL/src/render/opengl/SDL_render_gl.c ^
SDL/src/render/opengl/SDL_shaders_gl.c ^
SDL/src/render/opengles2/SDL_render_gles2.c ^
SDL/src/render/opengles2/SDL_shaders_gles2.c ^
SDL/src/sensor/windows/SDL_windowssensor.c ^
SDL/src/thread/windows/SDL_syscond_cv.c ^
SDL/src/video/windows/SDL_windowsclipboard.c ^
SDL/src/video/windows/SDL_windowsevents.c ^
SDL/src/video/windows/SDL_windowsframebuffer.c ^
SDL/src/video/windows/SDL_windowskeyboard.c ^
SDL/src/video/windows/SDL_windowsmessagebox.c ^
SDL/src/video/windows/SDL_windowsmodes.c ^
SDL/src/video/windows/SDL_windowsmouse.c ^
SDL/src/video/windows/SDL_windowsopengl.c ^
SDL/src/video/windows/SDL_windowsopengles.c ^
SDL/src/video/windows/SDL_windowsshape.c ^
SDL/src/video/windows/SDL_windowsvideo.c ^
SDL/src/video/windows/SDL_windowsvulkan.c ^
SDL/src/video/windows/SDL_windowswindow.c ^
SDL/src/joystick/SDL_steam_virtual_gamepad.c ^
SDL/src/dynapi/SDL_dynapi.c ^
SDL/src/main/windows/SDL_windows_main.c

popd
